
set -e

HEADER="${SRCROOT}/Modules/RCTIPAddress.h"

echo "// This file is generated by a build script." > $HEADER
echo "// Updated on "`date` >> $HEADER
echo "" >> $HEADER

ip_address="`ifconfig en0 | grep "inet " | cut -d: -f2 | awk '{print $2}'`"
echo "#define LOCAL_IP_ADDRESS @\"${ip_address}\"" >> $HEADER

echo "Updated local IP: ${ip_address}"

if nc -w 5 -z ${ip_address} 8081 ; then
  if ! curl -s "http://${ip_address}:8081/status" | grep -q "packager-status:running" ; then
    echo "Port 8081 already in use, packager is either not running or not running correctly"
    exit 2
  fi
else
  open "$SRCROOT/../packager/launchPackager.command" || echo "Can't start packager automatically"
fi
